import type { UserStory } from '../types';

export const storiesEP01: UserStory[] = [
  {
    id: 'US-ACC-01',
    epicId: 'EP-01',
    title: 'Đăng ký tài khoản bằng email',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng mới',
    userStory:
      'Là khách hàng mới, tôi muốn đăng ký tài khoản bằng email và mật khẩu để có thể mua hàng và theo dõi đơn hàng.',
    objective:
      'Cho phép khách hàng mới tạo tài khoản trong hệ thống với email và mật khẩu bảo mật.',
    mainFlow: [
      'Khách hàng nhấn "Đăng ký" trên header',
      'Nhập họ tên, email và mật khẩu (≥8 ký tự, có chữ hoa, số)',
      'Hệ thống kiểm tra email chưa tồn tại',
      'Hệ thống gửi email xác thực đến địa chỉ đã nhập',
      'Khách hàng click link trong email để xác thực',
      'Tài khoản được kích hoạt, redirect về trang chủ đã đăng nhập',
    ],
    businessRules: [
      { id: 'BR-ACC-01', text: 'Email phải là định dạng hợp lệ và chưa tồn tại trong hệ thống.', group: 'Account' },
      { id: 'BR-ACC-02', text: 'Mật khẩu tối thiểu 8 ký tự, bao gồm ít nhất 1 chữ hoa và 1 số.', group: 'Account' },
      { id: 'BR-ACC-03', text: 'Link xác thực email có hiệu lực trong 24 giờ.', group: 'Account' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-ACC-01-01',
        given: 'Tôi là khách hàng chưa có tài khoản',
        when: 'Tôi điền đầy đủ thông tin hợp lệ và nhấn Đăng ký',
        then: 'Hệ thống gửi email xác thực và hiển thị thông báo "Vui lòng kiểm tra email"',
      },
      {
        id: 'AC-ACC-01-02',
        given: 'Tôi nhập email đã tồn tại',
        when: 'Tôi nhấn Đăng ký',
        then: 'Hệ thống hiển thị lỗi "Email này đã được đăng ký"',
      },
      {
        id: 'AC-ACC-01-03',
        given: 'Tôi click link xác thực trong email',
        when: 'Link còn hiệu lực (< 24h)',
        then: 'Tài khoản được kích hoạt và tôi được đăng nhập tự động',
      },
    ],
    edgeCases: [
      'Link xác thực hết hạn → hiển thị nút "Gửi lại email xác thực"',
      'Email bị từ chối bởi mail server → hiển thị lỗi tương ứng',
    ],
    outOfScope: ['Đăng ký bằng Facebook', 'Đăng ký bằng Apple ID'],
    dependencies: [],
    notes: ['Email xác thực sử dụng template riêng có logo thương hiệu'],
  },
  {
    id: 'US-ACC-02',
    epicId: 'EP-01',
    title: 'Đăng nhập bằng email',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng đã có tài khoản',
    userStory:
      'Là khách hàng đã đăng ký, tôi muốn đăng nhập bằng email và mật khẩu để truy cập tài khoản cá nhân.',
    objective: 'Xác thực khách hàng và cấp phép truy cập hệ thống.',
    mainFlow: [
      'Khách hàng nhấn "Đăng nhập" trên header',
      'Nhập email và mật khẩu',
      'Hệ thống xác thực thông tin đăng nhập',
      'Hệ thống tạo JWT token và lưu vào cookie/localStorage',
      'Redirect về trang trước đó hoặc trang chủ',
    ],
    businessRules: [
      { id: 'BR-ACC-04', text: 'Sau 5 lần đăng nhập sai, tài khoản bị khóa tạm thời 15 phút.', group: 'Account' },
      { id: 'BR-ACC-05', text: 'JWT access token có hiệu lực 1 giờ, refresh token 30 ngày.', group: 'Account' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-ACC-02-01',
        given: 'Tôi có tài khoản hợp lệ đã xác thực email',
        when: 'Tôi nhập đúng email và mật khẩu',
        then: 'Tôi được đăng nhập và redirect về trang chủ',
      },
      {
        id: 'AC-ACC-02-02',
        given: 'Tôi nhập sai mật khẩu',
        when: 'Tôi nhấn Đăng nhập',
        then: 'Hệ thống hiển thị thông báo "Sai email hoặc mật khẩu"',
      },
    ],
    edgeCases: ['Tài khoản chưa xác thực email → yêu cầu xác thực trước', 'Tài khoản bị vô hiệu hóa → thông báo liên hệ CSKH'],
    outOfScope: ['Đăng nhập bằng OTP SMS', 'Đăng nhập bằng fingerprint'],
    dependencies: ['US-ACC-01'],
    notes: ['Nhớ mật khẩu với "Remember me" checkbox (30 ngày)'],
  },
  {
    id: 'US-ACC-03',
    epicId: 'EP-01',
    title: 'Đăng nhập bằng Google OAuth',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng, tôi muốn đăng nhập bằng tài khoản Google để không cần nhớ mật khẩu riêng.',
    objective: 'Cung cấp phương thức đăng nhập nhanh qua Google OAuth 2.0.',
    mainFlow: [
      'Khách hàng nhấn "Đăng nhập bằng Google"',
      'Redirect sang trang xác thực Google',
      'Khách hàng chọn tài khoản Google và chấp thuận quyền',
      'Google callback trả về authorization code',
      'Backend đổi code lấy access token và profile info',
      'Tự động tạo tài khoản hoặc liên kết nếu email đã tồn tại',
      'Đăng nhập thành công, redirect về trang chủ',
    ],
    businessRules: [
      { id: 'BR-ACC-06', text: 'Nếu email Google đã tồn tại (đăng ký thường), tự động liên kết tài khoản.', group: 'Account' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-ACC-03-01',
        given: 'Tôi chưa có tài khoản',
        when: 'Tôi đăng nhập bằng Google lần đầu',
        then: 'Hệ thống tự tạo tài khoản từ thông tin Google và đăng nhập',
      },
    ],
    edgeCases: ['Google API không khả dụng → hiển thị thông báo và cho phép đăng nhập thường'],
    outOfScope: ['Facebook Login', 'Apple Login'],
    dependencies: ['US-ACC-01'],
    notes: ['Chỉ lấy profile cơ bản: name, email, avatar'],
  },
  {
    id: 'US-ACC-04',
    epicId: 'EP-01',
    title: 'Quản lý hồ sơ cá nhân',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng đã đăng nhập',
    userStory:
      'Là khách hàng đã đăng nhập, tôi muốn xem và cập nhật thông tin cá nhân (tên, SĐT, avatar) để hồ sơ luôn chính xác.',
    objective: 'Cho phép khách hàng tự quản lý thông tin cá nhân của mình.',
    mainFlow: [
      'Vào trang Profile',
      'Xem thông tin hiện tại: tên, email, SĐT, avatar',
      'Chỉnh sửa tên và SĐT',
      'Upload avatar mới (jpg/png, max 2MB)',
      'Nhấn Lưu → hệ thống cập nhật thông tin',
    ],
    businessRules: [
      { id: 'BR-ACC-07', text: 'Email không thể thay đổi sau khi đăng ký.', group: 'Account' },
      { id: 'BR-ACC-08', text: 'Avatar phải là file jpg/png, kích thước ≤ 2MB.', group: 'Account' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-ACC-04-01',
        given: 'Tôi đang ở trang Profile',
        when: 'Tôi cập nhật tên và nhấn Lưu',
        then: 'Thông tin được cập nhật và hiển thị ngay lập tức trên header',
      },
    ],
    edgeCases: ['Upload ảnh quá 2MB → hiển thị lỗi kích thước'],
    outOfScope: ['Xóa tài khoản tự thực hiện', 'Thay đổi email'],
    dependencies: ['US-ACC-01'],
    notes: [],
  },
  {
    id: 'US-ACC-05',
    epicId: 'EP-01',
    title: 'Quản lý danh sách địa chỉ giao hàng',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng đã đăng nhập',
    userStory:
      'Là khách hàng, tôi muốn thêm và quản lý nhiều địa chỉ giao hàng để thuận tiện khi checkout.',
    objective: 'Cho phép lưu trữ và quản lý nhiều địa chỉ giao hàng cho một tài khoản.',
    mainFlow: [
      'Vào trang Địa chỉ của tôi',
      'Nhấn "Thêm địa chỉ mới"',
      'Nhập: họ tên người nhận, SĐT, tỉnh/thành, quận/huyện, phường/xã, địa chỉ chi tiết',
      'Chọn địa chỉ mặc định (optional)',
      'Lưu địa chỉ',
    ],
    businessRules: [
      { id: 'BR-ACC-09', text: 'Mỗi tài khoản tối đa 5 địa chỉ giao hàng.', group: 'Account' },
      { id: 'BR-ACC-10', text: 'Phải có ít nhất 1 địa chỉ mặc định khi có địa chỉ.', group: 'Account' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-ACC-05-01',
        given: 'Tôi đã có ít hơn 5 địa chỉ',
        when: 'Tôi điền đầy đủ thông tin và lưu',
        then: 'Địa chỉ mới xuất hiện trong danh sách và có thể chọn khi checkout',
      },
    ],
    edgeCases: ['Đã có 5 địa chỉ → ẩn nút "Thêm địa chỉ" và thông báo đạt giới hạn'],
    outOfScope: ['Tích hợp API định vị GPS', 'Kiểm tra địa chỉ hợp lệ qua GHN/GHTK API'],
    dependencies: ['US-ACC-01'],
    notes: ['Địa chỉ mặc định được tự động điền khi checkout'],
  },
  {
    id: 'US-ACC-06',
    epicId: 'EP-01',
    title: 'Quên mật khẩu và đặt lại mật khẩu',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng chưa đăng nhập',
    userStory:
      'Là khách hàng quên mật khẩu, tôi muốn đặt lại mật khẩu qua email để truy cập lại tài khoản.',
    objective: 'Cung cấp luồng phục hồi tài khoản khi quên mật khẩu.',
    mainFlow: [
      'Nhấn "Quên mật khẩu" trên trang đăng nhập',
      'Nhập email đã đăng ký',
      'Hệ thống gửi email chứa link reset mật khẩu',
      'Khách hàng click link, nhập mật khẩu mới',
      'Mật khẩu được cập nhật, redirect về trang đăng nhập',
    ],
    businessRules: [
      { id: 'BR-ACC-11', text: 'Link reset mật khẩu có hiệu lực 1 giờ và chỉ dùng được 1 lần.', group: 'Account' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-ACC-06-01',
        given: 'Tôi nhập email hợp lệ đã đăng ký',
        when: 'Tôi nhấn "Gửi email đặt lại"',
        then: 'Email reset được gửi trong vòng 2 phút',
      },
    ],
    edgeCases: ['Email không tồn tại → vẫn hiện thông báo "kiểm tra email" (bảo mật, không tiết lộ)', 'Link đã dùng → hiển thị lỗi "Link không hợp lệ"'],
    outOfScope: ['Reset qua SMS OTP'],
    dependencies: ['US-ACC-01'],
    notes: [],
  },
];
