import type { UserStory } from '../types';

export const storiesEP03: UserStory[] = [
  {
    id: 'US-ADM-01',
    epicId: 'EP-03',
    title: 'Tạo và quản lý danh mục sản phẩm',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Admin',
    userStory:
      'Là admin, tôi muốn tạo và quản lý cây danh mục sản phẩm (Category Tree) để tổ chức hàng hóa có cấu trúc rõ ràng.',
    objective: 'Cung cấp giao diện CRUD cho hệ thống danh mục sản phẩm đa cấp.',
    mainFlow: [
      'Admin vào Admin Panel → Categories',
      'Xem cây danh mục hiện có',
      'Tạo danh mục mới: nhập tên, mô tả, chọn danh mục cha (nếu có), upload icon',
      'Thiết lập SEO slug tự động hoặc tùy chỉnh',
      'Publish/Unpublish danh mục',
    ],
    businessRules: [
      { id: 'BR-ADM-01', text: 'Slug danh mục phải unique trong toàn hệ thống.', group: 'Admin' },
      { id: 'BR-ADM-02', text: 'Không thể xóa danh mục có sản phẩm đang active.', group: 'Admin' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-ADM-01-01',
        given: 'Admin tạo danh mục "Nhẫn cưới" con của "Nhẫn"',
        when: 'Nhấn Lưu',
        then: 'Danh mục xuất hiện trong cây phân cấp và trên storefront',
      },
    ],
    edgeCases: ['Xóa danh mục có sub-category → cảnh báo và ngăn chặn'],
    outOfScope: ['Tự động mapping từ danh mục khác'],
    dependencies: [],
    notes: [],
  },
  {
    id: 'US-ADM-02',
    epicId: 'EP-03',
    title: 'Tạo sản phẩm mới với biến thể',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Admin',
    userStory:
      'Là admin, tôi muốn tạo sản phẩm mới với đầy đủ thông tin (ảnh, mô tả, biến thể, giá) để đưa hàng lên sàn.',
    objective: 'Cung cấp form tạo sản phẩm đầy đủ hỗ trợ product variant.',
    mainFlow: [
      'Admin vào Sản phẩm → Tạo mới',
      'Nhập thông tin cơ bản: tên, mô tả, danh mục',
      'Upload 1-10 ảnh sản phẩm (drag & drop)',
      'Thêm biến thể: chọn attribute (chất liệu, size), nhập SKU, giá, tồn kho cho từng variant',
      'Thiết lập trạng thái: Draft/Published',
      'Lưu sản phẩm',
    ],
    businessRules: [
      { id: 'BR-ADM-03', text: 'SKU phải unique toàn hệ thống.', group: 'Admin' },
      { id: 'BR-ADM-04', text: 'Mỗi sản phẩm phải có ít nhất 1 ảnh và 1 biến thể.', group: 'Admin' },
      { id: 'BR-ADM-05', text: 'Giá phải là số dương, không âm.', group: 'Admin' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-ADM-02-01',
        given: 'Admin điền đầy đủ thông tin hợp lệ',
        when: 'Nhấn Publish',
        then: 'Sản phẩm xuất hiện ngay trên storefront trong vòng 30 giây',
      },
    ],
    edgeCases: ['SKU trùng → lỗi inline tại field SKU', 'Upload ảnh > 5MB → lỗi size'],
    outOfScope: ['Import hàng loạt từ Excel/CSV'],
    dependencies: ['US-ADM-01'],
    notes: ['Tối đa 10 ảnh/sản phẩm, định dạng jpg/png/webp'],
  },
  {
    id: 'US-ADM-03',
    epicId: 'EP-03',
    title: 'Cập nhật thông tin và giá sản phẩm',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Admin',
    userStory:
      'Là admin, tôi muốn cập nhật thông tin và giá sản phẩm hiện có để đảm bảo thông tin luôn chính xác.',
    objective: 'Cho phép chỉnh sửa toàn bộ thông tin sản phẩm đã publish.',
    mainFlow: [
      'Admin tìm sản phẩm cần sửa',
      'Nhấn "Chỉnh sửa"',
      'Thay đổi thông tin, giá, ảnh hoặc tồn kho',
      'Lưu thay đổi',
      'Hệ thống cập nhật ngay trên storefront',
    ],
    businessRules: [
      { id: 'BR-ADM-06', text: 'Thay đổi giá không ảnh hưởng đến đơn hàng đang xử lý.', group: 'Admin' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-ADM-03-01',
        given: 'Sản phẩm đang published',
        when: 'Admin thay đổi giá và lưu',
        then: 'Giá mới hiển thị trên storefront ngay lập tức',
      },
    ],
    edgeCases: [],
    outOfScope: ['Lịch sử thay đổi giá (price history log)'],
    dependencies: ['US-ADM-02'],
    notes: [],
  },
  {
    id: 'US-ADM-04',
    epicId: 'EP-03',
    title: 'Quản lý tồn kho theo variant',
    priority: 'MUST',
    status: 'DONE',
    owner: 'BE',
    actor: 'Admin / Nhân viên kho',
    userStory:
      'Là admin, tôi muốn theo dõi và cập nhật tồn kho theo từng variant để tránh bán hàng không có hàng.',
    objective: 'Cung cấp giao diện quản lý tồn kho real-time theo SKU/variant.',
    mainFlow: [
      'Admin vào mục Tồn kho',
      'Xem bảng tồn kho: SKU, tên variant, số lượng hiện tại, ngưỡng cảnh báo',
      'Cập nhật số lượng tồn kho',
      'Thiết lập ngưỡng cảnh báo tồn kho thấp',
    ],
    businessRules: [
      { id: 'BR-ADM-07', text: 'Tồn kho không được âm. Khi về 0, variant tự động chuyển "Hết hàng".', group: 'Admin' },
      { id: 'BR-ADM-08', text: 'Cảnh báo tồn kho thấp khi số lượng ≤ ngưỡng cài đặt (mặc định 5).', group: 'Admin' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-ADM-04-01',
        given: 'Tồn kho variant = 1 và khách mua 1',
        when: 'Đơn hàng được confirm',
        then: 'Tồn kho = 0 và variant hiển thị "Hết hàng" trên storefront',
      },
    ],
    edgeCases: ['Cập nhật tồn kho đồng thời từ nhiều đơn hàng → optimistic locking'],
    outOfScope: ['Tích hợp với hệ thống kho vật lý (WMS)'],
    dependencies: ['US-ADM-02'],
    notes: [],
  },
  {
    id: 'US-ADM-05',
    epicId: 'EP-03',
    title: 'Ẩn/Hiện và xóa sản phẩm',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Admin',
    userStory:
      'Là admin, tôi muốn ẩn hoặc xóa sản phẩm không còn kinh doanh để giữ catalog gọn gàng.',
    objective: 'Cung cấp quản lý vòng đời sản phẩm: Draft/Published/Archived.',
    mainFlow: [
      'Admin vào danh sách sản phẩm',
      'Chọn sản phẩm cần ẩn/xóa',
      'Chuyển trạng thái sang "Ẩn" hoặc "Lưu trữ"',
    ],
    businessRules: [
      { id: 'BR-ADM-09', text: 'Không thể xóa vĩnh viễn sản phẩm có đơn hàng lịch sử. Chỉ có thể Archive.', group: 'Admin' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-ADM-05-01',
        given: 'Sản phẩm đang published',
        when: 'Admin chuyển sang "Ẩn"',
        then: 'Sản phẩm biến mất khỏi storefront trong vòng 30 giây',
      },
    ],
    edgeCases: ['Sản phẩm trong giỏ hàng của khách bị ẩn → vẫn giữ trong giỏ nhưng thông báo "Không còn bán"'],
    outOfScope: ['Khôi phục từ thùng rác'],
    dependencies: ['US-ADM-02'],
    notes: [],
  },
  {
    id: 'US-ADM-06',
    epicId: 'EP-03',
    title: 'Tìm kiếm và lọc sản phẩm trong Admin',
    priority: 'SHOULD',
    status: 'DONE',
    owner: 'FE',
    actor: 'Admin',
    userStory:
      'Là admin, tôi muốn tìm kiếm và lọc sản phẩm trong trang quản trị để nhanh chóng tìm thấy sản phẩm cần quản lý.',
    objective: 'Cung cấp tìm kiếm và bộ lọc trong Admin Product List.',
    mainFlow: [
      'Admin vào Admin → Sản phẩm',
      'Tìm kiếm theo tên, SKU',
      'Lọc theo danh mục, trạng thái, khoảng giá',
      'Sắp xếp theo tên, giá, tồn kho, ngày tạo',
    ],
    businessRules: [],
    acceptanceCriteria: [
      {
        id: 'AC-ADM-06-01',
        given: 'Admin tìm kiếm "SKU-001"',
        when: 'Enter',
        then: 'Chỉ hiển thị sản phẩm có SKU-001',
      },
    ],
    edgeCases: [],
    outOfScope: ['Export danh sách ra Excel'],
    dependencies: ['US-ADM-02'],
    notes: [],
  },
];
