import type { UserStory } from '../types';

// ── EP-04: Curated Sets ──────────────────────────────────────────────────────
export const storiesEP04: UserStory[] = [
  {
    id: 'US-SET-01',
    epicId: 'EP-04',
    title: 'Admin tạo bộ trang sức (Curated Set)',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Admin',
    userStory:
      'Là admin, tôi muốn tạo bộ trang sức phối hợp (curated set) gồm nhiều sản phẩm để khách hàng mua theo bộ với ưu đãi.',
    objective: 'Cung cấp giao diện admin tạo và quản lý Curated Set.',
    mainFlow: [
      'Admin vào Bộ sưu tập → Tạo bộ mới',
      'Đặt tên, mô tả và ảnh đại diện cho bộ',
      'Tìm kiếm và thêm 2-6 sản phẩm vào bộ',
      'Thiết lập giá bộ (tổng hoặc giá ưu đãi riêng)',
      'Publish bộ',
    ],
    businessRules: [
      { id: 'BR-SET-01', text: 'Mỗi set phải có từ 2 đến 6 sản phẩm.', group: 'Set' },
      { id: 'BR-SET-02', text: 'Giá set phải thấp hơn tổng giá các sản phẩm lẻ.', group: 'Set' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-SET-01-01',
        given: 'Admin tạo set "Bộ nhẫn cưới đôi" với 2 nhẫn',
        when: 'Publish',
        then: 'Set xuất hiện trên trang Bộ sưu tập của storefront',
      },
    ],
    edgeCases: ['Sản phẩm trong set bị xóa → set chuyển Draft, admin nhận notification'],
    outOfScope: ['Khách hàng tự tạo set'],
    dependencies: ['US-ADM-02'],
    notes: [],
  },
  {
    id: 'US-SET-02',
    epicId: 'EP-04',
    title: 'Xem trang Bộ sưu tập trên Storefront',
    priority: 'MUST',
    status: 'DONE',
    owner: 'FE',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng, tôi muốn xem các bộ trang sức phối hợp để tìm ý tưởng và mua theo bộ.',
    objective: 'Hiển thị trang Curated Sets với preview các sản phẩm trong bộ.',
    mainFlow: [
      'Khách hàng vào menu "Bộ sưu tập"',
      'Xem danh sách các set với ảnh đại diện, tên, giá bộ và tiết kiệm được bao nhiêu',
      'Click vào set để xem chi tiết',
      'Trang chi tiết hiển thị từng sản phẩm trong bộ',
    ],
    businessRules: [
      { id: 'BR-SET-03', text: 'Hiển thị badge "Tiết kiệm X%" so với mua lẻ.', group: 'Set' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-SET-02-01',
        given: 'Có set đang published',
        when: 'Khách vào trang Bộ sưu tập',
        then: 'Set hiển thị với ảnh, tên, giá và phần trăm tiết kiệm',
      },
    ],
    edgeCases: ['Set hết hàng (1 sản phẩm hết) → badge "Tạm hết hàng"'],
    outOfScope: [],
    dependencies: ['US-SET-01', 'US-CAT-04'],
    notes: [],
  },
  {
    id: 'US-SET-03',
    epicId: 'EP-04',
    title: 'Thêm cả bộ vào giỏ hàng',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng xem chi tiết bộ trang sức, tôi muốn thêm cả bộ vào giỏ hàng chỉ với một lần nhấn.',
    objective: 'Cho phép thêm toàn bộ sản phẩm trong set vào giỏ với giá set.',
    mainFlow: [
      'Khách hàng đang xem chi tiết set',
      'Nhấn "Thêm cả bộ vào giỏ"',
      'Hệ thống kiểm tra tồn kho tất cả sản phẩm trong set',
      'Thêm từng sản phẩm với giá set vào giỏ hàng',
      'Thông báo thành công và cập nhật badge giỏ hàng',
    ],
    businessRules: [
      { id: 'BR-SET-04', text: 'Khi mua set, giá áp dụng là giá set, không phải giá lẻ từng sản phẩm.', group: 'Set' },
      { id: 'BR-SET-05', text: 'Nếu bất kỳ sản phẩm nào trong set hết hàng, không cho thêm cả set.', group: 'Set' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-SET-03-01',
        given: 'Tất cả sản phẩm trong set còn hàng',
        when: 'Nhấn "Thêm cả bộ vào giỏ"',
        then: 'Tất cả sản phẩm được thêm với giá set, hiển thị badge set trong giỏ',
      },
    ],
    edgeCases: ['Giỏ hàng đã có 1 sản phẩm trong set → cảnh báo trùng và hỏi cách xử lý'],
    outOfScope: [],
    dependencies: ['US-SET-02'],
    notes: [],
  },
  {
    id: 'US-SET-04',
    epicId: 'EP-04',
    title: 'Tùy chỉnh sản phẩm trong Set trước khi mua',
    priority: 'SHOULD',
    status: 'DONE',
    owner: 'FE',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng, tôi muốn thay thế một sản phẩm trong set (ví dụ đổi size nhẫn) trước khi cho vào giỏ.',
    objective: 'Cho phép khách chọn variant cụ thể cho từng item trong set.',
    mainFlow: [
      'Trên trang chi tiết set, mỗi sản phẩm có dropdown chọn size/variant',
      'Khách chọn variant mong muốn cho từng sản phẩm',
      'Nhấn "Thêm cả bộ vào giỏ"',
    ],
    businessRules: [
      { id: 'BR-SET-06', text: 'Giá set giữ nguyên khi đổi variant trong cùng sản phẩm.', group: 'Set' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-SET-04-01',
        given: 'Set gồm nhẫn nữ và nhẫn nam',
        when: 'Tôi chọn size 12 cho nhẫn nữ và size 18 cho nhẫn nam',
        then: 'Đúng 2 variant được thêm vào giỏ với giá set',
      },
    ],
    edgeCases: ['Variant được chọn hết hàng → cảnh báo và không cho thêm giỏ'],
    outOfScope: ['Thay thế sản phẩm bằng sản phẩm khác ngoài set'],
    dependencies: ['US-SET-03'],
    notes: [],
  },
  {
    id: 'US-SET-05',
    epicId: 'EP-04',
    title: 'Admin theo dõi hiệu quả Curated Set',
    priority: 'NICE',
    status: 'DONE',
    owner: 'Both',
    actor: 'Admin',
    userStory:
      'Là admin, tôi muốn xem thống kê doanh thu và lượt mua của từng Curated Set để đánh giá hiệu quả.',
    objective: 'Dashboard hiển thị KPI của từng set: lượt xem, lượt mua, doanh thu.',
    mainFlow: [
      'Admin vào Bộ sưu tập → chọn set cụ thể',
      'Xem tab Analytics: lượt xem, lượt click "Thêm vào giỏ", conversion rate, doanh thu',
    ],
    businessRules: [],
    acceptanceCriteria: [
      {
        id: 'AC-SET-05-01',
        given: 'Có dữ liệu mua hàng trong 30 ngày',
        when: 'Admin xem analytics set',
        then: 'Hiển thị đúng tổng doanh thu và số lượng bộ đã bán',
      },
    ],
    edgeCases: [],
    outOfScope: ['A/B testing set'],
    dependencies: ['US-SET-01'],
    notes: [],
  },
];

// ── EP-05: AI Stylist ─────────────────────────────────────────────────────────
export const storiesEP05: UserStory[] = [
  {
    id: 'US-AI-01',
    epicId: 'EP-05',
    title: 'Nhập thông tin để nhận gợi ý trang sức từ AI',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng, tôi muốn nhập dịp, phong cách và ngân sách để AI gợi ý trang sức phù hợp, giúp tôi quyết định dễ hơn.',
    objective: 'Cung cấp form nhập liệu đơn giản cho AI Jewelry Stylist feature.',
    mainFlow: [
      'Khách hàng vào trang "AI Stylist" từ menu',
      'Chọn dịp: Sinh nhật / Đám cưới / Kỷ niệm / Thường ngày / Khác',
      'Chọn phong cách: Cổ điển / Hiện đại / Bohemian / Tối giản',
      'Nhập ngân sách: kéo range slider (500K - 100M VND)',
      'Nhấn "Nhận gợi ý"',
    ],
    businessRules: [
      { id: 'BR-AI-01', text: 'AI phải trả kết quả trong ≤ 3 giây.', group: 'AI Stylist' },
      { id: 'BR-AI-02', text: 'Tất cả gợi ý phải nằm trong ngưỡng ngân sách ±10%.', group: 'AI Stylist' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-AI-01-01',
        given: 'Tôi chọn "Đám cưới", "Cổ điển", ngân sách 10 triệu',
        when: 'Nhấn "Nhận gợi ý"',
        then: 'Trong 3 giây, hiển thị ít nhất 3 gợi ý sản phẩm trong khoảng 9-11 triệu',
      },
    ],
    edgeCases: ['AI timeout > 3s → hiển thị fallback rule-based gợi ý'],
    outOfScope: ['Gợi ý cho nam giới (v1)', 'Multi-language support'],
    dependencies: ['US-CAT-04'],
    notes: ['LLM model: sử dụng API bên thứ 3 (GPT hoặc Gemini)'],
  },
  {
    id: 'US-AI-02',
    epicId: 'EP-05',
    title: 'Hiển thị kết quả gợi ý từ AI',
    priority: 'MUST',
    status: 'DONE',
    owner: 'FE',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng, tôi muốn xem kết quả gợi ý trang sức từ AI theo dạng card đẹp với lý do gợi ý để dễ lựa chọn.',
    objective: 'UI hiển thị kết quả gợi ý AI hấp dẫn với explanation text.',
    mainFlow: [
      'Sau khi nhận gợi ý, trang chuyển sang màn hình kết quả',
      'Hiển thị 3-6 gợi ý theo dạng card: ảnh sản phẩm, tên, giá, lý do AI gợi ý',
      'Mỗi card có nút "Thêm vào giỏ" và "Xem chi tiết"',
    ],
    businessRules: [
      { id: 'BR-AI-03', text: 'Mỗi gợi ý phải kèm explanation text từ AI (1-2 câu).', group: 'AI Stylist' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-AI-02-01',
        given: 'AI đã trả kết quả',
        when: 'Màn hình kết quả hiển thị',
        then: 'Mỗi sản phẩm có ảnh, tên, giá và ít nhất 1 câu lý do gợi ý bằng tiếng Việt',
      },
    ],
    edgeCases: ['AI trả về sản phẩm hết hàng → lọc ra, bổ sung sản phẩm khác'],
    outOfScope: ['Gợi ý theo màu da, vóc dáng'],
    dependencies: ['US-AI-01'],
    notes: [],
  },
  {
    id: 'US-AI-03',
    epicId: 'EP-05',
    title: 'Yêu thích và không thích gợi ý để AI học',
    priority: 'SHOULD',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng, tôi muốn đánh dấu "thích/không thích" từng gợi ý của AI để lần sau nhận gợi ý phù hợp hơn.',
    objective: 'Thu thập feedback để cải thiện chất lượng gợi ý AI trong tương lai.',
    mainFlow: [
      'Mỗi card gợi ý có nút 👍 / 👎',
      'Khách nhấn để đánh giá',
      'Hệ thống lưu feedback kèm session context',
    ],
    businessRules: [],
    acceptanceCriteria: [
      {
        id: 'AC-AI-03-01',
        given: 'Tôi xem kết quả gợi ý',
        when: 'Tôi nhấn 👎 vào 1 card',
        then: 'Card mờ đi và có thể bị thay thế bằng gợi ý khác',
      },
    ],
    edgeCases: [],
    outOfScope: ['Realtime model retraining'],
    dependencies: ['US-AI-02'],
    notes: ['Feedback lưu vào analytics để báo cáo sau'],
  },
  {
    id: 'US-AI-04',
    epicId: 'EP-05',
    title: 'Smart Set Builder từ gợi ý AI',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng nhận gợi ý từ AI, tôi muốn tổng hợp các sản phẩm AI gợi ý thành một bộ trang sức tùy chỉnh để thêm vào giỏ hàng.',
    objective: 'Flagship sub-feature: Smart Set Builder cho phép build custom set từ gợi ý AI.',
    mainFlow: [
      'Từ màn hình kết quả AI, nhấn "Tạo bộ trang sức"',
      'Smart Set Builder mở ra với các sản phẩm AI gợi ý được pre-populated',
      'Khách có thể bỏ sản phẩm hoặc thêm sản phẩm khác từ catalog',
      'Tổng giá cập nhật real-time',
      'Nhấn "Thêm cả bộ vào giỏ"',
    ],
    businessRules: [
      { id: 'BR-AI-04', text: 'Smart Set phải có 2-6 sản phẩm.', group: 'AI Stylist' },
      { id: 'BR-AI-05', text: 'Tổng giá Smart Set không áp dụng giảm giá tự động (không phải Curated Set của admin).', group: 'AI Stylist' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-AI-04-01',
        given: 'AI đã gợi ý 4 sản phẩm',
        when: 'Tôi mở Smart Set Builder',
        then: '4 sản phẩm được pre-populate, tổng giá hiển thị đúng và tôi có thể xóa/thêm sản phẩm',
      },
    ],
    edgeCases: ['Sản phẩm thêm vào đã có trong set → thông báo trùng'],
    outOfScope: ['Lưu Smart Set để dùng lại sau', 'Share Smart Set'],
    dependencies: ['US-AI-02', 'US-SET-03'],
    notes: ['Đây là Flagship feature của đồ án'],
  },
  {
    id: 'US-AI-05',
    epicId: 'EP-05',
    title: 'Lịch sử gợi ý AI',
    priority: 'NICE',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng đã đăng nhập',
    userStory:
      'Là khách hàng, tôi muốn xem lại lịch sử các lần nhận gợi ý AI trước đó để tham khảo lại.',
    objective: 'Lưu và hiển thị lịch sử các session gợi ý AI.',
    mainFlow: [
      'Khách vào trang "Lịch sử gợi ý"',
      'Xem danh sách các session theo thời gian',
      'Click vào session để xem lại gợi ý và input',
    ],
    businessRules: [
      { id: 'BR-AI-06', text: 'Lịch sử lưu tối đa 20 session gần nhất.', group: 'AI Stylist' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-AI-05-01',
        given: 'Tôi đã dùng AI Stylist 3 lần',
        when: 'Vào trang Lịch sử gợi ý',
        then: 'Hiển thị 3 session với ngày, input và kết quả gợi ý',
      },
    ],
    edgeCases: [],
    outOfScope: [],
    dependencies: ['US-AI-01', 'US-ACC-01'],
    notes: [],
  },
  {
    id: 'US-AI-06',
    epicId: 'EP-05',
    title: 'Fallback khi AI không khả dụng',
    priority: 'MUST',
    status: 'DONE',
    owner: 'BE',
    actor: 'Hệ thống',
    userStory:
      'Là hệ thống, khi AI service không khả dụng hoặc timeout, tôi muốn tự động fallback sang rule-based gợi ý để không làm gián đoạn trải nghiệm khách hàng.',
    objective: 'Đảm bảo availability của tính năng AI Stylist kể cả khi LLM API lỗi.',
    mainFlow: [
      'AI service call timeout hoặc trả lỗi',
      'Hệ thống fallback sang rule-based engine',
      'Rule-based lọc sản phẩm theo dịp + khoảng giá từ config',
      'Trả về kết quả trong ≤ 500ms',
      'Hiển thị thông báo nhỏ "Đang dùng gợi ý offline"',
    ],
    businessRules: [
      { id: 'BR-AI-07', text: 'Fallback phải kích hoạt khi AI không trả kết quả sau 3 giây.', group: 'AI Stylist' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-AI-06-01',
        given: 'AI API trả lỗi 500',
        when: 'Khách nhấn "Nhận gợi ý"',
        then: 'Trong 3.5 giây, fallback results hiển thị với banner "Gợi ý cơ bản"',
      },
    ],
    edgeCases: ['Fallback rule cũng lỗi → hiển thị thông báo "Hệ thống tạm bảo trì"'],
    outOfScope: ['Circuit breaker tự phục hồi'],
    dependencies: ['US-AI-01'],
    notes: [],
  },
];

// ── EP-06: Cart & Pricing ─────────────────────────────────────────────────────
export const storiesEP06: UserStory[] = [
  {
    id: 'US-CART-01',
    epicId: 'EP-06',
    title: 'Thêm sản phẩm SKU vào giỏ hàng',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng, tôi muốn thêm sản phẩm với variant đã chọn vào giỏ hàng để chuẩn bị mua.',
    objective: 'Cho phép thêm SKU cụ thể vào giỏ hàng với số lượng mong muốn.',
    mainFlow: [
      'Khách chọn variant trên trang chi tiết sản phẩm',
      'Nhập số lượng (mặc định 1)',
      'Nhấn "Thêm vào giỏ"',
      'Hệ thống kiểm tra tồn kho',
      'Thêm item vào giỏ, badge số lượng trên header +1',
      'Toast notification "Đã thêm vào giỏ hàng"',
    ],
    businessRules: [
      { id: 'BR-CART-01', text: 'Số lượng thêm không được vượt tồn kho hiện có.', group: 'Cart' },
      { id: 'BR-CART-02', text: 'Tổng số lượng 1 SKU trong giỏ không vượt tồn kho.', group: 'Cart' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-CART-01-01',
        given: 'SKU còn 5 hàng, giỏ chưa có SKU này',
        when: 'Thêm 3 vào giỏ',
        then: 'Giỏ có 3 sản phẩm, badge header = 3',
      },
      {
        id: 'AC-CART-01-02',
        given: 'SKU chỉ còn 2 hàng',
        when: 'Thêm 5 vào giỏ',
        then: 'Lỗi "Chỉ còn 2 sản phẩm trong kho"',
      },
    ],
    edgeCases: ['Thêm vào giỏ khi chưa chọn variant → thông báo "Vui lòng chọn size"'],
    outOfScope: ['Saved for later', 'Cart sharing'],
    dependencies: ['US-CAT-04'],
    notes: [],
  },
  {
    id: 'US-CART-02',
    epicId: 'EP-06',
    title: 'Xem và quản lý giỏ hàng',
    priority: 'MUST',
    status: 'DONE',
    owner: 'FE',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng, tôi muốn xem toàn bộ sản phẩm trong giỏ, thay đổi số lượng và xóa sản phẩm để kiểm soát đơn hàng trước khi thanh toán.',
    objective: 'Trang giỏ hàng đầy đủ chức năng CRUD với tính tổng tiền real-time.',
    mainFlow: [
      'Khách nhấn icon giỏ hàng trên header',
      'Trang giỏ hàng hiển thị danh sách item: ảnh, tên, variant, giá, số lượng',
      'Thay đổi số lượng bằng nút +/-',
      'Xóa item bằng nút X',
      'Tổng tiền cập nhật ngay sau mỗi thay đổi',
    ],
    businessRules: [
      { id: 'BR-CART-03', text: 'Giỏ hàng persist sau logout (lưu theo session/userId).', group: 'Cart' },
      { id: 'BR-CART-04', text: 'Tối đa 20 SKU khác nhau trong giỏ.', group: 'Cart' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-CART-02-01',
        given: 'Giỏ có 3 sản phẩm',
        when: 'Tôi tăng số lượng sản phẩm 1 lên 2',
        then: 'Tổng tiền cập nhật ngay, không cần refresh',
      },
    ],
    edgeCases: ['Sản phẩm trong giỏ bị hết hàng sau khi thêm → cảnh báo màu đỏ "Hết hàng"'],
    outOfScope: ['Lưu giỏ hàng để dùng sau'],
    dependencies: ['US-CART-01'],
    notes: [],
  },
  {
    id: 'US-CART-03',
    epicId: 'EP-06',
    title: 'Tính tổng giá và hiển thị cước phí vận chuyển ước tính',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng xem giỏ hàng, tôi muốn thấy tổng giá hàng, phí vận chuyển ước tính và tổng thanh toán để biết số tiền cần chuẩn bị.',
    objective: 'Tính và hiển thị chi tiết giá trên trang giỏ hàng.',
    mainFlow: [
      'Trang giỏ hiển thị: Tổng tiền hàng / Phí vận chuyển ước tính / Giảm giá voucher / Tổng cộng',
      'Phí vận chuyển ước tính theo địa chỉ mặc định (nếu đã đăng nhập)',
    ],
    businessRules: [
      { id: 'BR-CART-05', text: 'Phí vận chuyển ước tính sẽ được xác nhận chính xác ở bước checkout.', group: 'Cart' },
      { id: 'BR-CART-06', text: 'Miễn phí vận chuyển khi đơn hàng ≥ 5.000.000 VND.', group: 'Cart' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-CART-03-01',
        given: 'Tổng tiền hàng là 4.500.000 VND',
        when: 'Xem giỏ hàng',
        then: 'Phí vận chuyển 30.000 VND hiển thị, tổng = 4.530.000 VND',
      },
    ],
    edgeCases: ['Chưa có địa chỉ → phí vận chuyển hiển thị "Sẽ tính khi checkout"'],
    outOfScope: ['Tích hợp GHN/GHTK realtime pricing'],
    dependencies: ['US-CART-02'],
    notes: [],
  },
  {
    id: 'US-CART-04',
    epicId: 'EP-06',
    title: 'Áp dụng voucher vào giỏ hàng',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng, tôi muốn nhập mã voucher giảm giá vào giỏ hàng để được ưu đãi khi mua.',
    objective: 'Validate và áp dụng voucher code trước khi checkout.',
    mainFlow: [
      'Trên trang giỏ hàng, nhập mã voucher vào ô text',
      'Nhấn "Áp dụng"',
      'Hệ thống validate: kiểm tra tồn tại, còn hạn, điều kiện đơn hàng tối thiểu',
      'Nếu hợp lệ: hiển thị số tiền giảm và trừ vào tổng',
    ],
    businessRules: [
      { id: 'BR-CART-07', text: 'Chỉ được áp dụng 1 voucher tại một thời điểm.', group: 'Cart' },
      { id: 'BR-CART-08', text: 'Voucher phải thỏa điều kiện đơn hàng tối thiểu.', group: 'Cart' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-CART-04-01',
        given: 'Voucher SAVE10 giảm 10%, đơn tối thiểu 1 triệu, đơn tôi là 2 triệu',
        when: 'Nhập SAVE10 và nhấn Áp dụng',
        then: 'Giảm 200.000 VND, tổng = 1.800.000 VND',
      },
      {
        id: 'AC-CART-04-02',
        given: 'Voucher đã hết hạn',
        when: 'Nhập mã',
        then: 'Lỗi "Voucher đã hết hạn"',
      },
    ],
    edgeCases: ['Voucher đã dùng đủ lượt → lỗi "Voucher đã hết lượt"'],
    outOfScope: ['Voucher tự động áp dụng (chưa có)'],
    dependencies: ['US-CART-02'],
    notes: [],
  },
  {
    id: 'US-CART-05',
    epicId: 'EP-06',
    title: 'Giỏ hàng persistent sau đăng nhập/đăng xuất',
    priority: 'MUST',
    status: 'DONE',
    owner: 'BE',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng đã thêm hàng vào giỏ rồi đăng xuất, tôi muốn giỏ hàng vẫn còn khi đăng nhập lại để không phải thêm lại từ đầu.',
    objective: 'Đảm bảo cart persistence cho user đã đăng nhập.',
    mainFlow: [
      'Khách chưa đăng nhập thêm sản phẩm vào giỏ (localStorage)',
      'Đăng nhập → hệ thống merge giỏ localStorage với giỏ server',
      'Đăng xuất → giỏ hàng vẫn được lưu server-side',
      'Đăng nhập lại → giỏ hàng được restore',
    ],
    businessRules: [
      { id: 'BR-CART-09', text: 'Khi merge giỏ, nếu SKU trùng thì cộng số lượng (không vượt tồn kho).', group: 'Cart' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-CART-05-01',
        given: 'Tôi có 3 sản phẩm trong giỏ rồi đăng xuất',
        when: 'Tôi đăng nhập lại',
        then: 'Giỏ hàng vẫn còn đủ 3 sản phẩm',
      },
    ],
    edgeCases: ['Sản phẩm trong giỏ đã hết hàng sau thời gian → giữ trong giỏ nhưng cảnh báo'],
    outOfScope: [],
    dependencies: ['US-ACC-01', 'US-CART-01'],
    notes: [],
  },
];
