import type { UserStory } from '../types';

// ── EP-07: Promotion & Voucher ───────────────────────────────────────────────
export const storiesEP07: UserStory[] = [
  {
    id: 'US-PROMO-01',
    epicId: 'EP-07',
    title: 'Admin tạo voucher giảm giá',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Admin',
    userStory:
      'Là admin, tôi muốn tạo voucher giảm giá (% hoặc số tiền cố định) với điều kiện và thời hạn để chạy khuyến mãi.',
    objective: 'CRUD voucher với đầy đủ cấu hình: type, value, limit, expiry, conditions.',
    mainFlow: [
      'Admin vào Khuyến mãi → Tạo voucher',
      'Nhập mã voucher (hoặc auto-generate)',
      'Chọn loại: Giảm % hoặc Giảm tiền cố định',
      'Nhập giá trị giảm, đơn hàng tối thiểu, số lượt tối đa',
      'Chọn ngày bắt đầu và kết thúc',
      'Publish voucher',
    ],
    businessRules: [
      { id: 'BR-PROMO-01', text: 'Mã voucher phải unique, không phân biệt hoa thường.', group: 'Promotion' },
      { id: 'BR-PROMO-02', text: 'Giảm % tối đa 70%. Giảm cố định không vượt giá trị đơn hàng.', group: 'Promotion' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-PROMO-01-01',
        given: 'Admin tạo voucher SUMMER20 giảm 20%, đơn tối thiểu 500K, 100 lượt',
        when: 'Publish',
        then: 'Voucher active và khách hàng có thể nhập mã này khi checkout',
      },
    ],
    edgeCases: ['Mã voucher trùng → lỗi inline', 'Ngày kết thúc trước ngày bắt đầu → validation error'],
    outOfScope: ['Tặng voucher tự động khi đủ điều kiện (loyalty)'],
    dependencies: [],
    notes: [],
  },
  {
    id: 'US-PROMO-02',
    epicId: 'EP-07',
    title: 'Flash Sale với countdown timer',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Admin / Khách hàng',
    userStory:
      'Là admin, tôi muốn tạo Flash Sale có giới hạn thời gian để tạo urgency. Là khách hàng, tôi muốn thấy countdown timer để quyết định nhanh.',
    objective: 'Flash Sale feature với countdown timer thời gian thực trên storefront.',
    mainFlow: [
      'Admin tạo Flash Sale: chọn sản phẩm, % giảm, thời gian bắt đầu/kết thúc, số lượng',
      'Hệ thống tự động activate/deactivate Flash Sale đúng giờ',
      'Trên storefront, sản phẩm Flash Sale có badge và countdown timer',
      'Sau khi hết giờ hoặc hết số lượng, giá trở về bình thường',
    ],
    businessRules: [
      { id: 'BR-PROMO-03', text: 'Countdown timer cập nhật mỗi giây phía client (không real-time server push).', group: 'Promotion' },
      { id: 'BR-PROMO-04', text: 'Khi hết số lượng Flash Sale, badge biến mất, giá trở về giá gốc ngay.', group: 'Promotion' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-PROMO-02-01',
        given: 'Flash Sale còn 2 giờ',
        when: 'Khách xem trang sản phẩm',
        then: 'Hiển thị countdown "1:59:59" và giá giảm, cập nhật mỗi giây',
      },
    ],
    edgeCases: ['Khách thêm Flash Sale vào giỏ nhưng hết thời gian trước khi checkout → cảnh báo và cập nhật giá gốc'],
    outOfScope: ['Limit per user cho Flash Sale'],
    dependencies: ['US-ADM-02'],
    notes: [],
  },
  {
    id: 'US-PROMO-03',
    epicId: 'EP-07',
    title: 'Kiểm tra và áp dụng voucher khi checkout',
    priority: 'MUST',
    status: 'DONE',
    owner: 'BE',
    actor: 'Hệ thống',
    userStory:
      'Là hệ thống, khi khách hàng checkout với voucher, tôi muốn validate lại voucher server-side để ngăn gian lận.',
    objective: 'Server-side voucher validation an toàn tại thời điểm checkout.',
    mainFlow: [
      'Khi khách confirm đơn hàng, server re-validate voucher',
      'Kiểm tra: còn hiệu lực, còn lượt, đơn đạt tối thiểu, user chưa dùng',
      'Nếu invalid → reject order, thông báo lý do',
      'Nếu valid → apply discount, trừ lượt dùng',
    ],
    businessRules: [
      { id: 'BR-PROMO-05', text: 'Validation phải xảy ra ngay trước khi tạo payment intent.', group: 'Promotion' },
      { id: 'BR-PROMO-06', text: 'Lượt dùng voucher chỉ được trừ sau khi payment thành công.', group: 'Promotion' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-PROMO-03-01',
        given: 'Voucher đã được dùng hết lượt',
        when: 'Khách checkout với voucher đó',
        then: 'Server reject, trả lỗi "Voucher đã hết lượt sử dụng"',
      },
    ],
    edgeCases: ['Race condition: 2 user dùng voucher cùng lúc khi còn 1 lượt → chỉ 1 người được'],
    outOfScope: [],
    dependencies: ['US-PROMO-01', 'US-CART-04'],
    notes: ['Sử dụng database transaction để tránh race condition'],
  },
  {
    id: 'US-PROMO-04',
    epicId: 'EP-07',
    title: 'Admin xem báo cáo sử dụng voucher',
    priority: 'SHOULD',
    status: 'DONE',
    owner: 'Both',
    actor: 'Admin',
    userStory:
      'Là admin, tôi muốn xem báo cáo sử dụng voucher (số lượt đã dùng, doanh thu bị giảm) để đánh giá hiệu quả.',
    objective: 'Dashboard voucher analytics cho admin.',
    mainFlow: [
      'Admin vào Khuyến mãi → Báo cáo',
      'Xem bảng: mã voucher, tổng lượt dùng, tổng tiền giảm, doanh thu sau giảm',
      'Lọc theo khoảng thời gian',
    ],
    businessRules: [],
    acceptanceCriteria: [
      {
        id: 'AC-PROMO-04-01',
        given: 'Voucher SUMMER20 đã được dùng 50 lần',
        when: 'Admin xem báo cáo',
        then: 'Hiển thị đúng 50 lượt, tổng tiền giảm và doanh thu',
      },
    ],
    edgeCases: [],
    outOfScope: ['Export Excel'],
    dependencies: ['US-PROMO-01'],
    notes: [],
  },
  {
    id: 'US-PROMO-05',
    epicId: 'EP-07',
    title: 'Tự động áp dụng promotion theo điều kiện',
    priority: 'SHOULD',
    status: 'DONE',
    owner: 'BE',
    actor: 'Hệ thống',
    userStory:
      'Là hệ thống, tôi muốn tự động áp dụng khuyến mãi khi đơn hàng đủ điều kiện (không cần mã) để tăng trải nghiệm.',
    objective: 'Auto-apply promotion rules mà không cần nhập mã voucher.',
    mainFlow: [
      'Khách thêm sản phẩm vào giỏ',
      'Hệ thống kiểm tra promotion rules active',
      'Nếu đơn đủ điều kiện (ví dụ: mua 2 tặng 1, hoặc giảm 5% đơn ≥ 3 triệu)',
      'Tự động áp dụng và thông báo "Bạn được giảm 5%"',
    ],
    businessRules: [
      { id: 'BR-PROMO-07', text: 'Auto-promotion không thể stack với voucher khách nhập tay.', group: 'Promotion' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-PROMO-05-01',
        given: 'Có promotion rule: đơn ≥ 3 triệu giảm 5%',
        when: 'Tổng giỏ đạt 3 triệu',
        then: 'Banner "Bạn đã đủ điều kiện giảm 5%" tự hiện và áp dụng',
      },
    ],
    edgeCases: [],
    outOfScope: [],
    dependencies: ['US-PROMO-01', 'US-CART-03'],
    notes: [],
  },
  {
    id: 'US-PROMO-06',
    epicId: 'EP-07',
    title: 'Admin quản lý danh sách Promotion',
    priority: 'MUST',
    status: 'DONE',
    owner: 'FE',
    actor: 'Admin',
    userStory:
      'Là admin, tôi muốn xem, tìm kiếm, kích hoạt/tắt các chương trình khuyến mãi trong một giao diện thống nhất.',
    objective: 'Promotion management list view trong Admin Panel.',
    mainFlow: [
      'Admin vào Khuyến mãi',
      'Xem bảng tất cả promotion/voucher với trạng thái',
      'Toggle active/inactive',
      'Tìm kiếm, lọc theo trạng thái, loại',
    ],
    businessRules: [],
    acceptanceCriteria: [
      {
        id: 'AC-PROMO-06-01',
        given: 'Có 20 voucher',
        when: 'Admin lọc "Đang active"',
        then: 'Chỉ hiển thị voucher có trạng thái Active',
      },
    ],
    edgeCases: [],
    outOfScope: [],
    dependencies: ['US-PROMO-01'],
    notes: [],
  },
];

// ── EP-08: Checkout & Payment ─────────────────────────────────────────────────
export const storiesEP08: UserStory[] = [
  {
    id: 'US-CHK-01',
    epicId: 'EP-08',
    title: 'Multi-step Checkout Flow',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng, tôi muốn hoàn tất đơn hàng qua quy trình checkout rõ ràng từng bước (địa chỉ → vận chuyển → thanh toán) để không bị nhầm lẫn.',
    objective: 'Multi-step checkout flow với 3 bước rõ ràng.',
    mainFlow: [
      'Từ giỏ hàng → nhấn "Tiến hành thanh toán"',
      'Bước 1 - Địa chỉ: chọn hoặc nhập địa chỉ giao hàng',
      'Bước 2 - Vận chuyển: chọn phương thức (Giao thường / Nhanh / Hỏa tốc)',
      'Bước 3 - Thanh toán: chọn phương thức (VNPay / Momo / COD)',
      'Xem tóm tắt đơn hàng và xác nhận',
    ],
    businessRules: [
      { id: 'BR-CHK-01', text: 'Phải có địa chỉ giao hàng trước khi sang bước tiếp theo.', group: 'Checkout' },
      { id: 'BR-CHK-02', text: 'Khi xác nhận đơn, hệ thống tạm giữ tồn kho trong 15 phút chờ thanh toán.', group: 'Checkout' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-CHK-01-01',
        given: 'Tôi đã chọn địa chỉ, phương thức vận chuyển và thanh toán',
        when: 'Nhấn "Đặt hàng"',
        then: 'Đơn hàng được tạo với status PENDING và redirect đến trang thanh toán',
      },
    ],
    edgeCases: ['Sản phẩm hết hàng trong thời gian checkout → thông báo và hủy bước thanh toán'],
    outOfScope: ['Checkout guest (không cần đăng nhập)'],
    dependencies: ['US-CART-02', 'US-ACC-05'],
    notes: [],
  },
  {
    id: 'US-CHK-02',
    epicId: 'EP-08',
    title: 'Thanh toán qua VNPay',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng, tôi muốn thanh toán đơn hàng qua VNPay để sử dụng thẻ ATM/tín dụng hoặc QR code.',
    objective: 'Tích hợp VNPay payment gateway với callback xử lý kết quả.',
    mainFlow: [
      'Khách chọn "Thanh toán qua VNPay" và nhấn "Đặt hàng"',
      'Backend tạo VNPay payment URL',
      'Redirect khách sang trang thanh toán VNPay',
      'Khách hoàn tất thanh toán',
      'VNPay callback về backend với kết quả',
      'Backend cập nhật trạng thái đơn hàng PAID',
      'Redirect khách về trang "Đặt hàng thành công"',
    ],
    businessRules: [
      { id: 'BR-CHK-03', text: 'Payment timeout 15 phút. Quá thời gian → đơn hàng tự hủy, tồn kho được hoàn trả.', group: 'Checkout' },
      { id: 'BR-CHK-04', text: 'Phải verify callback signature từ VNPay để tránh giả mạo.', group: 'Checkout' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-CHK-02-01',
        given: 'Đơn hàng tạo thành công',
        when: 'Thanh toán VNPay thành công',
        then: 'Đơn hàng chuyển sang PAID, email xác nhận được gửi trong 1 phút',
      },
    ],
    edgeCases: ['VNPay trả FAILED → đơn giữ PENDING, khách được retry', 'Network lỗi sau redirect → webhook bắt kịp'],
    outOfScope: ['Hoàn tiền tự động qua VNPay'],
    dependencies: ['US-CHK-01'],
    notes: ['Sử dụng VNPay Sandbox cho môi trường test'],
  },
  {
    id: 'US-CHK-03',
    epicId: 'EP-08',
    title: 'Thanh toán qua Momo',
    priority: 'SHOULD',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng, tôi muốn thanh toán qua ví điện tử Momo bằng QR code hoặc deep link.',
    objective: 'Tích hợp Momo payment gateway.',
    mainFlow: [
      'Khách chọn "Thanh toán qua Momo"',
      'Backend tạo Momo payment request',
      'Hiển thị QR code hoặc redirect app Momo',
      'Momo IPN callback về backend',
      'Cập nhật đơn hàng và thông báo',
    ],
    businessRules: [
      { id: 'BR-CHK-05', text: 'Verify Momo signature trước khi cập nhật đơn hàng.', group: 'Checkout' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-CHK-03-01',
        given: 'Đơn hàng PENDING',
        when: 'Khách thanh toán Momo thành công',
        then: 'Đơn chuyển PAID và email xác nhận gửi tự động',
      },
    ],
    edgeCases: ['App Momo không cài → fallback QR code trên web'],
    outOfScope: [],
    dependencies: ['US-CHK-01'],
    notes: [],
  },
  {
    id: 'US-CHK-04',
    epicId: 'EP-08',
    title: 'Trang xác nhận đơn hàng thành công',
    priority: 'MUST',
    status: 'DONE',
    owner: 'FE',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng đã thanh toán xong, tôi muốn thấy trang xác nhận đơn hàng với mã đơn và tóm tắt để yên tâm đặt hàng thành công.',
    objective: 'Order confirmation page sau khi thanh toán thành công.',
    mainFlow: [
      'Sau thanh toán thành công, redirect về /order-success',
      'Hiển thị: mã đơn hàng, danh sách sản phẩm, địa chỉ giao hàng, tổng tiền',
      'Nút "Theo dõi đơn hàng" và "Tiếp tục mua sắm"',
    ],
    businessRules: [],
    acceptanceCriteria: [
      {
        id: 'AC-CHK-04-01',
        given: 'Thanh toán thành công',
        when: 'Redirect về order success page',
        then: 'Hiển thị đúng mã đơn, sản phẩm đã mua và địa chỉ giao hàng',
      },
    ],
    edgeCases: ['Direct access vào /order-success không có session → redirect về trang chủ'],
    outOfScope: [],
    dependencies: ['US-CHK-02'],
    notes: ['Email xác nhận được gửi song song với hiển thị trang này'],
  },
  {
    id: 'US-CHK-05',
    epicId: 'EP-08',
    title: 'Xử lý thanh toán thất bại và retry',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng bị lỗi thanh toán, tôi muốn được thông báo rõ ràng và có cơ hội thử lại mà không mất đơn hàng.',
    objective: 'Xử lý payment failure gracefully với retry flow.',
    mainFlow: [
      'Payment gateway trả về lỗi',
      'Hiển thị trang thông báo thất bại với lý do',
      'Cung cấp 2 option: Thử lại thanh toán / Đổi phương thức thanh toán',
      'Đơn hàng giữ status PENDING trong 15 phút',
    ],
    businessRules: [
      { id: 'BR-CHK-06', text: 'Đơn hàng PENDING có thể retry thanh toán trong 15 phút.', group: 'Checkout' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-CHK-05-01',
        given: 'Thanh toán VNPay thất bại',
        when: 'Redirect về trang thất bại',
        then: 'Hiển thị lý do thất bại và nút "Thử lại" dẫn về trang thanh toán',
      },
    ],
    edgeCases: ['Timeout 15 phút → đơn hủy tự động, thông báo khách'],
    outOfScope: ['Blacklist thẻ lỗi nhiều lần'],
    dependencies: ['US-CHK-02'],
    notes: [],
  },
  {
    id: 'US-CHK-06',
    epicId: 'EP-08',
    title: 'Gửi email xác nhận đơn hàng',
    priority: 'MUST',
    status: 'DONE',
    owner: 'BE',
    actor: 'Hệ thống',
    userStory:
      'Là hệ thống, sau khi đơn hàng được xác nhận thanh toán, tôi muốn tự động gửi email xác nhận chi tiết đơn hàng cho khách.',
    objective: 'Transactional email xác nhận đơn hàng tự động sau payment success.',
    mainFlow: [
      'Payment callback xử lý thành công',
      'Trigger email service gửi confirmation email',
      'Email chứa: mã đơn, sản phẩm, địa chỉ, tổng tiền, ETA giao hàng',
      'Email gửi trong ≤ 1 phút sau thanh toán',
    ],
    businessRules: [
      { id: 'BR-CHK-07', text: 'Email xác nhận phải gửi trong ≤ 1 phút sau payment success.', group: 'Checkout' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-CHK-06-01',
        given: 'Đơn hàng vừa thanh toán thành công',
        when: 'Sau tối đa 1 phút',
        then: 'Khách nhận email với đầy đủ thông tin đơn hàng',
      },
    ],
    edgeCases: ['Email gửi thất bại → retry 3 lần với delay 5 phút', 'Email bounced → log và alert admin'],
    outOfScope: ['SMS notification'],
    dependencies: ['US-CHK-02'],
    notes: ['Template email thiết kế riêng theo branding jewelry'],
  },
];

// ── EP-09: Orders, Stock & Pre-order ─────────────────────────────────────────
export const storiesEP09: UserStory[] = [
  {
    id: 'US-ORD-01',
    epicId: 'EP-09',
    title: 'Xem lịch sử đơn hàng cá nhân',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng đã đăng nhập',
    userStory:
      'Là khách hàng, tôi muốn xem danh sách đơn hàng đã đặt và trạng thái hiện tại để theo dõi quá trình giao hàng.',
    objective: 'Trang "Đơn hàng của tôi" với danh sách và trạng thái.',
    mainFlow: [
      'Khách vào Tài khoản → Đơn hàng của tôi',
      'Xem danh sách đơn sắp xếp mới nhất đầu',
      'Mỗi đơn hiển thị: mã, ngày đặt, tổng tiền, trạng thái',
      'Click vào đơn để xem chi tiết',
    ],
    businessRules: [
      { id: 'BR-ORD-01', text: 'Trạng thái đơn: PENDING → CONFIRMED → SHIPPING → DELIVERED → CANCELLED.', group: 'Order' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-ORD-01-01',
        given: 'Tôi có 5 đơn hàng',
        when: 'Vào trang Đơn hàng của tôi',
        then: 'Hiển thị 5 đơn theo thứ tự mới nhất trước, với trạng thái chính xác',
      },
    ],
    edgeCases: [],
    outOfScope: ['Reorder từ đơn cũ'],
    dependencies: ['US-CHK-01'],
    notes: [],
  },
  {
    id: 'US-ORD-02',
    epicId: 'EP-09',
    title: 'Theo dõi chi tiết đơn hàng và lịch sử trạng thái',
    priority: 'MUST',
    status: 'DONE',
    owner: 'FE',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng, tôi muốn xem chi tiết đơn hàng bao gồm lịch sử thay đổi trạng thái để biết đơn đang ở giai đoạn nào.',
    objective: 'Order detail page với timeline trạng thái.',
    mainFlow: [
      'Click vào đơn hàng cụ thể',
      'Xem: danh sách sản phẩm, địa chỉ giao, phương thức thanh toán, tổng tiền',
      'Timeline trạng thái: Đặt hàng → Xác nhận → Đang giao → Đã giao',
    ],
    businessRules: [],
    acceptanceCriteria: [
      {
        id: 'AC-ORD-02-01',
        given: 'Đơn hàng đang SHIPPING',
        when: 'Xem chi tiết đơn',
        then: 'Timeline hiển thị 3 bước đã hoàn thành và bước "Đang giao" đang active',
      },
    ],
    edgeCases: [],
    outOfScope: ['Tracking code đơn vị vận chuyển real-time'],
    dependencies: ['US-ORD-01'],
    notes: [],
  },
  {
    id: 'US-ORD-03',
    epicId: 'EP-09',
    title: 'Admin quản lý và cập nhật trạng thái đơn hàng',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Admin / Nhân viên kho',
    userStory:
      'Là admin, tôi muốn xem danh sách đơn hàng và cập nhật trạng thái để quản lý vòng đời đơn hàng.',
    objective: 'Admin Order Management với CRUD trạng thái.',
    mainFlow: [
      'Admin vào Đơn hàng',
      'Tìm kiếm/lọc đơn theo trạng thái, ngày, khách hàng',
      'Cập nhật trạng thái đơn',
      'In phiếu đóng gói (in-scope cơ bản)',
    ],
    businessRules: [
      { id: 'BR-ORD-02', text: 'Không thể hủy đơn đã DELIVERED.', group: 'Order' },
      { id: 'BR-ORD-03', text: 'Khi hủy đơn, tồn kho được hoàn trả tự động.', group: 'Order' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-ORD-03-01',
        given: 'Đơn hàng CONFIRMED',
        when: 'Admin chuyển sang SHIPPING',
        then: 'Trạng thái cập nhật và khách nhận email thông báo "Đơn hàng đang giao"',
      },
    ],
    edgeCases: [],
    outOfScope: ['Tích hợp API GHN/GHTK tự động cập nhật trạng thái'],
    dependencies: ['US-CHK-01'],
    notes: [],
  },
  {
    id: 'US-ORD-04',
    epicId: 'EP-09',
    title: 'Hủy đơn hàng',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng / Admin',
    userStory:
      'Là khách hàng, tôi muốn hủy đơn hàng khi đơn chưa được giao để không phải nhận hàng không mong muốn.',
    objective: 'Cho phép hủy đơn trong giới hạn thời gian với hoàn trả tồn kho.',
    mainFlow: [
      'Khách vào chi tiết đơn hàng',
      'Nhấn "Hủy đơn" (chỉ hiển thị khi đơn PENDING/CONFIRMED)',
      'Nhập lý do hủy',
      'Xác nhận hủy',
      'Đơn chuyển CANCELLED, tồn kho hoàn trả',
    ],
    businessRules: [
      { id: 'BR-ORD-04', text: 'Khách chỉ có thể hủy khi đơn ở trạng thái PENDING hoặc CONFIRMED.', group: 'Order' },
      { id: 'BR-ORD-05', text: 'Khi hủy đơn đã thanh toán, cần tạo refund request (manual xử lý).', group: 'Order' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-ORD-04-01',
        given: 'Đơn hàng PENDING',
        when: 'Khách hủy đơn',
        then: 'Đơn chuyển CANCELLED, tồn kho được cộng lại, email thông báo hủy gửi đến khách',
      },
    ],
    edgeCases: ['Hủy đơn đã SHIPPING → không cho phép, hiển thị thông báo liên hệ CSKH'],
    outOfScope: ['Hoàn tiền tự động'],
    dependencies: ['US-ORD-01'],
    notes: [],
  },
  {
    id: 'US-ORD-05',
    epicId: 'EP-09',
    title: 'Pre-order sản phẩm chưa có hàng',
    priority: 'SHOULD',
    status: 'DONE',
    owner: 'Both',
    actor: 'Khách hàng',
    userStory:
      'Là khách hàng, tôi muốn đặt trước sản phẩm chưa về hàng và đặt cọc để giữ chỗ.',
    objective: 'Pre-order feature với deposit payment.',
    mainFlow: [
      'Sản phẩm được admin đánh dấu "Pre-order" với ngày dự kiến',
      'Khách xem trang sản phẩm thấy badge "Pre-order" và "Dự kiến: DD/MM/YYYY"',
      'Nhấn "Đặt trước" → nhập số lượng',
      'Thanh toán deposit (30% giá trị) qua VNPay/Momo',
      'Khi hàng về, admin notify khách và khách thanh toán phần còn lại',
    ],
    businessRules: [
      { id: 'BR-ORD-06', text: 'Deposit pre-order là 30% giá trị sản phẩm, không hoàn lại nếu khách hủy.', group: 'Order' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-ORD-05-01',
        given: 'Sản phẩm có pre-order enabled',
        when: 'Khách đặt trước và thanh toán deposit',
        then: 'Đơn pre-order tạo với status PRE_ORDER, khách nhận email xác nhận deposit',
      },
    ],
    edgeCases: ['Admin đổi ngày dự kiến → email thông báo tự động gửi cho tất cả pre-order của sản phẩm đó'],
    outOfScope: ['Hoàn deposit khi hủy pre-order'],
    dependencies: ['US-CHK-01', 'US-ADM-02'],
    notes: [],
  },
  {
    id: 'US-ORD-06',
    epicId: 'EP-09',
    title: 'Admin theo dõi tồn kho real-time',
    priority: 'MUST',
    status: 'DONE',
    owner: 'BE',
    actor: 'Admin',
    userStory:
      'Là admin, tôi muốn xem tồn kho real-time theo SKU để phát hiện sản phẩm sắp hết hàng và ra quyết định nhập hàng.',
    objective: 'Inventory dashboard real-time với cảnh báo tồn kho thấp.',
    mainFlow: [
      'Admin vào Tồn kho',
      'Xem bảng tồn kho: SKU, tên, tồn hiện tại, đang giữ (pending orders), khả dụng thực',
      'Cột cảnh báo màu đỏ khi tồn kho ≤ ngưỡng',
    ],
    businessRules: [
      { id: 'BR-ORD-07', text: 'Tồn kho khả dụng = Tồn kho hiện tại - Số lượng đang giữ bởi PENDING orders.', group: 'Order' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-ORD-06-01',
        given: 'SKU có 3 sản phẩm và 2 đơn PENDING giữ 2 sản phẩm',
        when: 'Admin xem tồn kho',
        then: 'Hiển thị Tồn kho: 3, Đang giữ: 2, Khả dụng: 1',
      },
    ],
    edgeCases: [],
    outOfScope: ['Tự động tạo PO nhập hàng'],
    dependencies: ['US-ADM-04'],
    notes: [],
  },
];

// ── EP-10: Admin Operations ───────────────────────────────────────────────────
export const storiesEP10: UserStory[] = [
  {
    id: 'US-OPS-01',
    epicId: 'EP-10',
    title: 'Admin Dashboard KPI Overview',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Admin',
    userStory:
      'Là admin, tôi muốn xem dashboard tổng quan với các KPI chính (doanh thu, đơn hàng, khách mới) để nắm nhanh tình hình kinh doanh.',
    objective: 'Admin dashboard với KPI cards và biểu đồ doanh thu.',
    mainFlow: [
      'Admin đăng nhập vào Admin Panel',
      'Trang Dashboard hiển thị: Doanh thu hôm nay / tuần / tháng',
      'Tổng đơn hàng, đơn đang xử lý, tỷ lệ hoàn thành',
      'Số khách mới trong 30 ngày',
      'Biểu đồ doanh thu 30 ngày',
    ],
    businessRules: [],
    acceptanceCriteria: [
      {
        id: 'AC-OPS-01-01',
        given: 'Admin đăng nhập lần đầu trong ngày',
        when: 'Trang Dashboard load',
        then: 'Hiển thị đúng tổng doanh thu hôm nay và số đơn pending',
      },
    ],
    edgeCases: [],
    outOfScope: ['Advanced BI với drill-down', 'Export báo cáo Excel'],
    dependencies: [],
    notes: [],
  },
  {
    id: 'US-OPS-02',
    epicId: 'EP-10',
    title: 'Quản lý tài khoản khách hàng',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Admin',
    userStory:
      'Là admin, tôi muốn xem danh sách và thông tin chi tiết khách hàng, kích hoạt/vô hiệu hóa tài khoản khi cần thiết.',
    objective: 'Customer management trong Admin Panel.',
    mainFlow: [
      'Admin vào Khách hàng',
      'Xem danh sách với: tên, email, ngày đăng ký, tổng đơn, trạng thái',
      'Tìm kiếm theo tên, email',
      'Xem chi tiết: lịch sử đơn hàng, địa chỉ, thông tin cá nhân',
      'Toggle kích hoạt/vô hiệu hóa tài khoản',
    ],
    businessRules: [
      { id: 'BR-OPS-01', text: 'Tài khoản bị vô hiệu hóa không thể đăng nhập.', group: 'Admin Ops' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-OPS-02-01',
        given: 'Khách hàng vi phạm điều khoản',
        when: 'Admin vô hiệu hóa tài khoản',
        then: 'Khách không thể đăng nhập và thấy thông báo "Tài khoản bị vô hiệu hóa"',
      },
    ],
    edgeCases: [],
    outOfScope: ['Merge tài khoản', 'Export danh sách khách hàng'],
    dependencies: ['US-ACC-01'],
    notes: [],
  },
  {
    id: 'US-OPS-03',
    epicId: 'EP-10',
    title: 'Báo cáo doanh thu và sản phẩm bán chạy',
    priority: 'SHOULD',
    status: 'DONE',
    owner: 'Both',
    actor: 'Admin',
    userStory:
      'Là admin, tôi muốn xem báo cáo doanh thu theo khoảng thời gian và danh sách sản phẩm bán chạy để ra quyết định kinh doanh.',
    objective: 'Basic analytics report: revenue by period và top products.',
    mainFlow: [
      'Admin vào Báo cáo',
      'Chọn khoảng thời gian (hôm nay / 7 ngày / 30 ngày / tùy chọn)',
      'Xem: Tổng doanh thu, số đơn, AOV (Average Order Value)',
      'Bảng top 10 sản phẩm bán chạy nhất',
    ],
    businessRules: [],
    acceptanceCriteria: [
      {
        id: 'AC-OPS-03-01',
        given: 'Chọn khoảng 30 ngày qua',
        when: 'Xem báo cáo',
        then: 'Doanh thu, số đơn và top sản phẩm hiển thị đúng theo period đó',
      },
    ],
    edgeCases: [],
    outOfScope: ['Cohort analysis', 'Customer LTV'],
    dependencies: ['US-OPS-01'],
    notes: [],
  },
  {
    id: 'US-OPS-04',
    epicId: 'EP-10',
    title: 'Quản lý đơn hàng từ Admin',
    priority: 'MUST',
    status: 'DONE',
    owner: 'Both',
    actor: 'Admin',
    userStory:
      'Là admin, tôi muốn tìm kiếm, lọc và xem chi tiết bất kỳ đơn hàng nào trong hệ thống để xử lý hỗ trợ khách hàng.',
    objective: 'Order search & detail view cho admin với full information.',
    mainFlow: [
      'Admin vào Đơn hàng',
      'Tìm kiếm theo mã đơn, email khách, tên sản phẩm',
      'Lọc theo trạng thái, phương thức thanh toán, khoảng ngày',
      'Xem chi tiết đơn bất kỳ',
    ],
    businessRules: [],
    acceptanceCriteria: [
      {
        id: 'AC-OPS-04-01',
        given: 'Có đơn hàng #ORD-00123',
        when: 'Admin tìm kiếm "ORD-00123"',
        then: 'Đơn hàng hiển thị ngay với full info',
      },
    ],
    edgeCases: [],
    outOfScope: ['Print order'],
    dependencies: ['US-ORD-03'],
    notes: [],
  },
  {
    id: 'US-OPS-05',
    epicId: 'EP-10',
    title: 'Quản lý phân quyền Admin',
    priority: 'SHOULD',
    status: 'DONE',
    owner: 'BE',
    actor: 'Super Admin',
    userStory:
      'Là Super Admin, tôi muốn tạo và phân quyền cho nhân viên admin theo vai trò để bảo mật hệ thống.',
    objective: 'RBAC cho admin: roles và permissions.',
    mainFlow: [
      'Super Admin vào Phân quyền',
      'Tạo tài khoản nhân viên với vai trò: Quản lý kho / Quản lý đơn hàng / Quản lý khuyến mãi',
      'Mỗi vai trò có quyền truy cập module tương ứng',
    ],
    businessRules: [
      { id: 'BR-OPS-02', text: 'Admin cấp thấp không thể truy cập module không được cấp phép.', group: 'Admin Ops' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-OPS-05-01',
        given: 'Nhân viên kho chỉ có quyền xem tồn kho',
        when: 'Truy cập module Khuyến mãi',
        then: 'Hệ thống trả 403 Forbidden',
      },
    ],
    edgeCases: [],
    outOfScope: ['Audit log chi tiết cho mọi action'],
    dependencies: [],
    notes: [],
  },
  {
    id: 'US-OPS-06',
    epicId: 'EP-10',
    title: 'Thông báo hệ thống và cảnh báo',
    priority: 'NICE',
    status: 'DONE',
    owner: 'Both',
    actor: 'Admin',
    userStory:
      'Là admin, tôi muốn nhận thông báo khi có đơn hàng mới, tồn kho thấp hoặc payment lỗi để xử lý kịp thời.',
    objective: 'In-app notification center cho admin.',
    mainFlow: [
      'Hệ thống tạo notification khi: đơn mới, tồn kho ≤ ngưỡng, payment failure',
      'Bell icon trên admin header hiển thị badge số chưa đọc',
      'Click vào xem danh sách thông báo',
    ],
    businessRules: [
      { id: 'BR-OPS-03', text: 'Thông báo tồn kho thấp chỉ gửi 1 lần/ngày/SKU để tránh spam.', group: 'Admin Ops' },
    ],
    acceptanceCriteria: [
      {
        id: 'AC-OPS-06-01',
        given: 'Đơn hàng mới được đặt',
        when: 'Admin đang ở trang bất kỳ trong Admin Panel',
        then: 'Badge số thông báo tăng lên 1 trong vòng 30 giây',
      },
    ],
    edgeCases: [],
    outOfScope: ['Push notification mobile app', 'Email notification cho admin'],
    dependencies: ['US-OPS-01'],
    notes: ['Real-time notification sử dụng WebSocket hoặc SSE'],
  },
];
